name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Construir o projeto
        run: npm run build

      - name: Enviar arquivos para Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}  # Nome do host FTP
          username: ${{ secrets.FTP_USERNAME }}  # Nome de usuário FTP atualizado
          password: ${{ secrets.FTP_PASSWORD }}  # Senha armazenada no GitHub Secrets
          local-dir: build/  # Pasta gerada pelo React
          server-dir: /public_html/ 
          exclude: |
            public/  # Diretório onde o site será hospedado
